//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.0.0
//
// Created by Quasar Development at 27-11-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>
#import "DDXMLElement.h"


@interface TIFPHARMA_ITEM_STATUS : NSObject
{
    int value;
    NSString* name;
}

+(TIFPHARMA_ITEM_STATUS*) createWithXml:(DDXMLNode*)node;
+(TIFPHARMA_ITEM_STATUS *)createWithString:(NSString *)value;
-(NSString*) stringValue;
-(NSString*) description;
-(int)getValue;
-(BOOL)isEqualTo:(TIFPHARMA_ITEM_STATUS *)item;
-(void) serialize:(DDXMLNode*)parent;
        
+(TIFPHARMA_ITEM_STATUS *) A;    
+(TIFPHARMA_ITEM_STATUS *) I;    
@end