//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.0.0
//
// Created by Quasar Development at 27-11-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "TIFRequestResultHandler.h"
#import "DDXML.h"



@interface TIFPHARMA_ITEM_COMP : NSObject 


@property (retain,nonatomic,getter=getNAME) NSString* NAME;

@property (retain,nonatomic,getter=getGLN) NSString* GLN;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(TIFRequestResultHandler*) __request;
+(TIFPHARMA_ITEM_COMP*) createWithXml:(DDXMLElement*)__node __request:(TIFRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(TIFRequestResultHandler*) __request;
@end