//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.0.0
//
// Created by Quasar Development at 27-11-2014
//
//---------------------------------------------------


#import "TIFHelper.h"
#import "TIFPHARMA_ITEM_COMP.h"


@implementation TIFPHARMA_ITEM_COMP
@synthesize NAME;
@synthesize GLN;

+ (TIFPHARMA_ITEM_COMP *)createWithXml:(DDXMLElement *)__node __request:(TIFRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(TIFRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([TIFHelper hasValue:__node name:@"NAME" index:0])
        {
            self.NAME = [[TIFHelper getNode:__node name:@"NAME" index:0] stringValue];
        }
        if([TIFHelper hasValue:__node name:@"GLN" index:0])
        {
            self.GLN = [[TIFHelper getNode:__node name:@"GLN" index:0] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(TIFRequestResultHandler*) __request
{

             
    DDXMLElement* __NAMEItemElement=[__request writeElement:NAME type:[NSString class] name:@"NAME" URI:@"http://swissindex.e-mediat.net/SwissindexPharma_out_V101" parent:__parent skipNullProperty:YES];
    if(__NAMEItemElement!=nil)
    {
        [__NAMEItemElement setStringValue:self.NAME];
    }
             
    DDXMLElement* __GLNItemElement=[__request writeElement:GLN type:[NSString class] name:@"GLN" URI:@"http://swissindex.e-mediat.net/SwissindexPharma_out_V101" parent:__parent skipNullProperty:YES];
    if(__GLNItemElement!=nil)
    {
        [__GLNItemElement setStringValue:self.GLN];
    }


}
@end
