//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.0.0
//
// Created by Quasar Development at 27-11-2014
//
//---------------------------------------------------


#import "TIFPHARMA_ITEM.h"
#import "TIFPHARMA_RESULT.h"
#import "TIFHelper.h"
#import "TIFPHARMA.h"


@implementation TIFPHARMA
@synthesize ITEM;
@synthesize RESULT;
@synthesize CREATION_DATETIME;

+ (TIFPHARMA *)createWithXml:(DDXMLElement *)__node __request:(TIFRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.ITEM =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(TIFRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([TIFHelper hasValue:__node name:@"ITEM"])
        {
            NSArray* __items=[__node elementsForName:@"ITEM"];
            for (DDXMLElement* __item in __items) {
                [self.ITEM addObject:(TIFPHARMA_ITEM*)[__request createObject:__item type:[TIFPHARMA_ITEM class]]];
            }
        }
        if([TIFHelper hasValue:__node name:@"RESULT" index:0])
        {
            self.RESULT = (TIFPHARMA_RESULT*)[__request createObject:[TIFHelper getNode:__node name:@"RESULT" index:0] type:[TIFPHARMA_RESULT class]];
        }
        if([TIFHelper hasAttribute:__node name:@"CREATION_DATETIME"])
        {
            self.CREATION_DATETIME = [TIFHelper getDate:[[TIFHelper getAttribute:__node name:@"CREATION_DATETIME"] stringValue]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(TIFRequestResultHandler*) __request
{

             
    if(self.ITEM!=nil)
    {
        for (TIFPHARMA_ITEM* __item in self.ITEM) {
            DDXMLElement* __ITEMItemElement=[__request writeElement:ITEM type:[TIFPHARMA_ITEM class] name:@"ITEM" URI:@"http://swissindex.e-mediat.net/SwissindexPharma_out_V101" parent:__parent skipNullProperty:NO];
            if(__ITEMItemElement!=nil)
            {
                [__item serialize:__ITEMItemElement __request: __request];
            }
        }
    }
             
    DDXMLElement* __RESULTItemElement=[__request writeElement:RESULT type:[TIFPHARMA_RESULT class] name:@"RESULT" URI:@"http://swissindex.e-mediat.net/SwissindexPharma_out_V101" parent:__parent skipNullProperty:YES];
    if(__RESULTItemElement!=nil)
    {
        [self.RESULT serialize:__RESULTItemElement __request: __request];
    }
             
    DDXMLNode* __CREATION_DATETIMEItemElement=[__request addAttribute:@"CREATION_DATETIME" URI:@"" stringValue:@"" element:__parent];
    [__CREATION_DATETIMEItemElement setStringValue:[TIFHelper getStringFromDate:self.CREATION_DATETIME]];


}
@end
