//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.0.0
//
// Created by Quasar Development at 27-11-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>
    
#import "TIFPHARMA_ITEM_STATUS.h"

@implementation TIFPHARMA_ITEM_STATUS

-(id) initWithEnum:(NSString*)itemName value:(int) itemValue
{
    if(self = [super init])
    {
        self->name=itemName;
        self->value=itemValue;
    }
    return self;
}

-(NSString*) stringValue
{
    return name;
}
    
-(NSString*) description
{
    return name;
}

-(int) getValue
{
    return value;
}

-(BOOL) isEqualTo:(TIFPHARMA_ITEM_STATUS *)item
{
    return [name isEqualToString:item->name];
}
   
-(void) serialize:(DDXMLNode*)parent
{
    [parent setStringValue:name];
}
     
+(TIFPHARMA_ITEM_STATUS*) A
{
    static TIFPHARMA_ITEM_STATUS* obj=nil;
    if(!obj)
    {
        obj=[[TIFPHARMA_ITEM_STATUS alloc] initWithEnum: @"A" value: 0];
    }
    return obj;
} 
+(TIFPHARMA_ITEM_STATUS*) I
{
    static TIFPHARMA_ITEM_STATUS* obj=nil;
    if(!obj)
    {
        obj=[[TIFPHARMA_ITEM_STATUS alloc] initWithEnum: @"I" value: 1];
    }
    return obj;
} 
    
+ (TIFPHARMA_ITEM_STATUS *)createWithXml:(DDXMLNode *)node
{
    return [TIFPHARMA_ITEM_STATUS createWithString:[node stringValue]];
}
    
+ (TIFPHARMA_ITEM_STATUS *)createWithString:(NSString *)value
{
    if([value isEqualToString:@"I"])
    {
        return [TIFPHARMA_ITEM_STATUS I];
    }
    return [TIFPHARMA_ITEM_STATUS A];   
}
    

@end
