//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.0.0
//
// Created by Quasar Development at 27-11-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class TIFPHARMA_ITEM;
@class TIFPHARMA_RESULT;
#import "TIFRequestResultHandler.h"
#import "DDXML.h"



@interface TIFPHARMA : NSObject 


@property (retain,nonatomic,getter=getITEM) NSMutableArray* ITEM;

@property (retain,nonatomic,getter=getRESULT) TIFPHARMA_RESULT* RESULT;

@property (retain,nonatomic,getter=getCREATION_DATETIME) NSDate* CREATION_DATETIME;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(TIFRequestResultHandler*) __request;
+(TIFPHARMA*) createWithXml:(DDXMLElement*)__node __request:(TIFRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(TIFRequestResultHandler*) __request;
@end