//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.0.0
//
// Created by Quasar Development at 27-11-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>
#import "DDXML.h"
@protocol TIFIReferenceObject
@end
    
@class TIFRequestResultHandler;
typedef void (^TIFCLB)(TIFRequestResultHandler *);

#define SOAPVERSION_10      1
#define SOAPVERSION_11      2
#define SOAPVERSION_12      3

@interface TIFRequestResultHandler : NSObject

@property BOOL EnableLogging;
@property (retain, nonatomic) DDXMLElement* Body;
@property (retain, nonatomic) DDXMLElement* Header;    
@property (retain, nonatomic) DDXMLElement* OutputHeader;
@property (retain, nonatomic) DDXMLElement* OutputBody;
@property (retain, nonatomic) NSError* OutputFault;
@property (nonatomic,copy) TIFCLB Callback;


-(id)init:(int) version;
-(id)createObject: (DDXMLElement*) node type:(Class) type;
-(NSString*) getEnvelopeString;
-(DDXMLDocument*) createEnvelopeXml;
-(id) createInstance:(Class) type node: (DDXMLNode*)node request :(TIFRequestResultHandler *)request;
-(DDXMLElement*) writeElement:(NSString*)name URI: (NSString*) URI parent:(DDXMLElement*) parent;
-(DDXMLElement*) writeElement:(id)obj type:(Class)type name: (NSString*)name URI: (NSString*) URI parent:(DDXMLElement*) parent skipNullProperty:(BOOL)skipNullProperty;
-(DDXMLNode*) addAttribute:(NSString*) name URI:(NSString*) URI stringValue:(NSString*) stringValue element:(DDXMLElement*) element;
-(void)setResponse:(NSData *)responseData response:(NSURLResponse*) response;
-(void) sendImplementation:(NSMutableURLRequest*) request callbackDelegate:(TIFCLB) callbackDelegate;
-(void)Cancel;    

-(void) sendImplementation:(NSMutableURLRequest*) request;

-(void) prepareRequest:(NSMutableURLRequest*)request;
@end