//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.0.0
//
// Created by Quasar Development at 27-11-2014
//
//---------------------------------------------------


#import "TIFws_Pharma_V101Soap12.h"
#import "TIFRequestResultHandler.h"
#import "TIFHelper.h"

@implementation TIFws_Pharma_V101Soap12
@synthesize Url,ShouldAddAdornments,Headers;
@synthesize EnableLogging;

- (id) init {
    if(self = [super init])
    {
        self.Url=@"https://swissindex.refdata.ch/Swissindex/Pharma/ws_Pharma_V101.asmx";
        self.ShouldAddAdornments=YES;
    }
    return self;
}

- (id) initWithUrl: (NSString*) url {
    if(self = [self init])
    {
        self.Url=url;
    }
    return self;
}

-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(TIFRequestResultHandler*) requestMgr
{
    [requestMgr sendImplementation:request];
}

-(TIFRequestResultHandler*) CreateRequestResultHandler
{
    TIFRequestResultHandler* handler= [[TIFRequestResultHandler alloc]init:SOAPVERSION_12];
    handler.EnableLogging = EnableLogging;
    return handler;
}

-(NSMutableURLRequest*) createRequest:(NSString *)__soapAction __request:(TIFRequestResultHandler*) __request
{
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    [__request prepareRequest:__requestObj];

    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];

    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];

    return __requestObj;
}


-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(TIFRequestResultHandler*) requestMgr callback:(void (^)(TIFRequestResultHandler *)) callback
{
    [requestMgr sendImplementation:request callbackDelegate:callback];
}

-(void) addAdornments:(DDXMLElement*)__methodElement
{
    if(ShouldAddAdornments)
    {
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"id" stringValue:@"o0"]];
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"c:root" stringValue:@"1"]];
    }
}

-(NSMutableURLRequest*) createDownloadAllRequest:(NSString*) lang __request:(TIFRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"lang" URI:@"http://swissindex.e-mediat.net/SwissindexPharma_out_V101" parent:__request.Body];
    [self addAdornments:__methodElement];
             
    DDXMLElement* __langItemElement=[__request writeElement:lang type:[NSString class] name:@"lang" URI:@"http://swissindex.e-mediat.net/SwissindexPharma_out_V101" parent:__methodElement skipNullProperty:NO];
    if(__langItemElement!=nil)
    {
        [__langItemElement setStringValue:lang];
    }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@"http://swissindex.e-mediat.net/SwissindexPharma_out_V101/DownloadAll"  __request:__request];
    return __requestObj;
    }
    
    -(TIFRequestResultHandler*) DownloadAllAsync:(NSString*) lang __target:(id) __target __handler:(SEL) __handler
    {
        TIFRequestResultHandler* __request = [self CreateRequestResultHandler];
        NSMutableURLRequest *__requestObj=[self createDownloadAllRequest:lang __request:__request];
        [self sendImplementation:__requestObj requestMgr:__request callback:^(TIFRequestResultHandler *__requestMgr) {
        id __res;
        if(__requestMgr.OutputFault==nil)
        {
            DDXMLElement *__result=[TIFHelper getResultElement:__request.OutputBody name:@"PHARMA"];
            __res= (TIFPHARMA*)[__request createObject:__result type:[TIFPHARMA class]];
        }
        else
        {
        __res=__requestMgr.OutputFault;
        }
        
        IMP imp = [__target methodForSelector:__handler];
        void (*func)(id, SEL,id) = (void *)imp;
        func(__target, __handler,__res);
        }];
        return __request;
    }
    
    -(TIFRequestResultHandler*) DownloadAllAsync:(NSString*) lang __target:(id<TIFSoapServiceResponse>) __target
    {
        TIFRequestResultHandler* __request = [self CreateRequestResultHandler];
        NSMutableURLRequest *__requestObj=[self createDownloadAllRequest:lang __request:__request];
        [self sendImplementation:__requestObj requestMgr:__request callback:^(TIFRequestResultHandler *__requestMgr) {
        if(__requestMgr.OutputFault==nil)
        {
            DDXMLElement *__result=[TIFHelper getResultElement:__request.OutputBody name:@"PHARMA"];
            [__target onSuccess:(TIFPHARMA*)[__request createObject:__result type:[TIFPHARMA class]] methodName:@"http://swissindex.e-mediat.net/SwissindexPharma_out_V101/DownloadAll"];
        }
        else
        {
        [__target onError:__requestMgr.OutputFault];
        }
        }];
        return __request;
    }
    
    -(TIFPHARMA*) DownloadAll:(NSString*) lang __error:(NSError**) __error
    {
        TIFRequestResultHandler* __request = [self CreateRequestResultHandler];
        NSMutableURLRequest *__requestObj=[self createDownloadAllRequest:lang __request:__request];
        [self sendImplementation:__requestObj requestMgr:__request ];
        if(__request.OutputFault!=nil)
        {
        if(__error)
        {
        *__error=__request.OutputFault;
        }
        return nil;
    }
        DDXMLElement *__result=[TIFHelper getResultElement:__request.OutputBody name:@"PHARMA"];
        return (TIFPHARMA*)[__request createObject:__result type:[TIFPHARMA class]];
    }
-(NSMutableURLRequest*) createDownloadByDateRequest:(NSDate*) mutationDate lang:(NSString*) lang __request:(TIFRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"mutationDate" URI:@"http://swissindex.e-mediat.net/SwissindexPharma_out_V101" parent:__request.Body];
    [self addAdornments:__methodElement];
             
    DDXMLElement* __mutationDateItemElement=[__request writeElement:mutationDate type:[NSDate class] name:@"mutationDate" URI:@"http://swissindex.e-mediat.net/SwissindexPharma_out_V101" parent:__methodElement skipNullProperty:NO];
    if(__mutationDateItemElement!=nil)
    {
        [__mutationDateItemElement setStringValue:[TIFHelper getStringFromDate:mutationDate]];
    }
             
    DDXMLElement* __langItemElement=[__request writeElement:lang type:[NSString class] name:@"lang" URI:@"http://swissindex.e-mediat.net/SwissindexPharma_out_V101" parent:__methodElement skipNullProperty:NO];
    if(__langItemElement!=nil)
    {
        [__langItemElement setStringValue:lang];
    }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@"http://swissindex.e-mediat.net/SwissindexPharma_out_V101/DownloadByDate"  __request:__request];
    return __requestObj;
    }
    
    -(TIFRequestResultHandler*) DownloadByDateAsync:(NSDate*) mutationDate lang:(NSString*) lang __target:(id) __target __handler:(SEL) __handler
    {
        TIFRequestResultHandler* __request = [self CreateRequestResultHandler];
        NSMutableURLRequest *__requestObj=[self createDownloadByDateRequest:mutationDate lang: lang __request:__request];
        [self sendImplementation:__requestObj requestMgr:__request callback:^(TIFRequestResultHandler *__requestMgr) {
        id __res;
        if(__requestMgr.OutputFault==nil)
        {
            DDXMLElement *__result=[TIFHelper getResultElement:__request.OutputBody name:@"PHARMA"];
            __res= (TIFPHARMA*)[__request createObject:__result type:[TIFPHARMA class]];
        }
        else
        {
        __res=__requestMgr.OutputFault;
        }
        
        IMP imp = [__target methodForSelector:__handler];
        void (*func)(id, SEL,id) = (void *)imp;
        func(__target, __handler,__res);
        }];
        return __request;
    }
    
    -(TIFRequestResultHandler*) DownloadByDateAsync:(NSDate*) mutationDate lang:(NSString*) lang __target:(id<TIFSoapServiceResponse>) __target
    {
        TIFRequestResultHandler* __request = [self CreateRequestResultHandler];
        NSMutableURLRequest *__requestObj=[self createDownloadByDateRequest:mutationDate lang: lang __request:__request];
        [self sendImplementation:__requestObj requestMgr:__request callback:^(TIFRequestResultHandler *__requestMgr) {
        if(__requestMgr.OutputFault==nil)
        {
            DDXMLElement *__result=[TIFHelper getResultElement:__request.OutputBody name:@"PHARMA"];
            [__target onSuccess:(TIFPHARMA*)[__request createObject:__result type:[TIFPHARMA class]] methodName:@"http://swissindex.e-mediat.net/SwissindexPharma_out_V101/DownloadByDate"];
        }
        else
        {
        [__target onError:__requestMgr.OutputFault];
        }
        }];
        return __request;
    }
    
    -(TIFPHARMA*) DownloadByDate:(NSDate*) mutationDate lang:(NSString*) lang __error:(NSError**) __error
    {
        TIFRequestResultHandler* __request = [self CreateRequestResultHandler];
        NSMutableURLRequest *__requestObj=[self createDownloadByDateRequest:mutationDate lang: lang __request:__request];
        [self sendImplementation:__requestObj requestMgr:__request ];
        if(__request.OutputFault!=nil)
        {
        if(__error)
        {
        *__error=__request.OutputFault;
        }
        return nil;
    }
        DDXMLElement *__result=[TIFHelper getResultElement:__request.OutputBody name:@"PHARMA"];
        return (TIFPHARMA*)[__request createObject:__result type:[TIFPHARMA class]];
    }
-(NSMutableURLRequest*) createGetByGTINRequest:(NSString*) GTIN lang:(NSString*) lang __request:(TIFRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"GTIN" URI:@"http://swissindex.e-mediat.net/SwissindexPharma_out_V101" parent:__request.Body];
    [self addAdornments:__methodElement];
             
    DDXMLElement* __GTINItemElement=[__request writeElement:GTIN type:[NSString class] name:@"GTIN" URI:@"http://swissindex.e-mediat.net/SwissindexPharma_out_V101" parent:__methodElement skipNullProperty:NO];
    if(__GTINItemElement!=nil)
    {
        [__GTINItemElement setStringValue:GTIN];
    }
             
    DDXMLElement* __langItemElement=[__request writeElement:lang type:[NSString class] name:@"lang" URI:@"http://swissindex.e-mediat.net/SwissindexPharma_out_V101" parent:__methodElement skipNullProperty:NO];
    if(__langItemElement!=nil)
    {
        [__langItemElement setStringValue:lang];
    }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@"http://swissindex.e-mediat.net/SwissindexPharma_out_V101/GetByGTIN"  __request:__request];
    return __requestObj;
    }
    
    -(TIFRequestResultHandler*) GetByGTINAsync:(NSString*) GTIN lang:(NSString*) lang __target:(id) __target __handler:(SEL) __handler
    {
        TIFRequestResultHandler* __request = [self CreateRequestResultHandler];
        NSMutableURLRequest *__requestObj=[self createGetByGTINRequest:GTIN lang: lang __request:__request];
        [self sendImplementation:__requestObj requestMgr:__request callback:^(TIFRequestResultHandler *__requestMgr) {
        id __res;
        if(__requestMgr.OutputFault==nil)
        {
            DDXMLElement *__result=[TIFHelper getResultElement:__request.OutputBody name:@"PHARMA"];
            __res= (TIFPHARMA*)[__request createObject:__result type:[TIFPHARMA class]];
        }
        else
        {
        __res=__requestMgr.OutputFault;
        }
        
        IMP imp = [__target methodForSelector:__handler];
        void (*func)(id, SEL,id) = (void *)imp;
        func(__target, __handler,__res);
        }];
        return __request;
    }
    
    -(TIFRequestResultHandler*) GetByGTINAsync:(NSString*) GTIN lang:(NSString*) lang __target:(id<TIFSoapServiceResponse>) __target
    {
        TIFRequestResultHandler* __request = [self CreateRequestResultHandler];
        NSMutableURLRequest *__requestObj=[self createGetByGTINRequest:GTIN lang: lang __request:__request];
        [self sendImplementation:__requestObj requestMgr:__request callback:^(TIFRequestResultHandler *__requestMgr) {
        if(__requestMgr.OutputFault==nil)
        {
            DDXMLElement *__result=[TIFHelper getResultElement:__request.OutputBody name:@"PHARMA"];
            [__target onSuccess:(TIFPHARMA*)[__request createObject:__result type:[TIFPHARMA class]] methodName:@"http://swissindex.e-mediat.net/SwissindexPharma_out_V101/GetByGTIN"];
        }
        else
        {
        [__target onError:__requestMgr.OutputFault];
        }
        }];
        return __request;
    }
    
    -(TIFPHARMA*) GetByGTIN:(NSString*) GTIN lang:(NSString*) lang __error:(NSError**) __error
    {
        TIFRequestResultHandler* __request = [self CreateRequestResultHandler];
        NSMutableURLRequest *__requestObj=[self createGetByGTINRequest:GTIN lang: lang __request:__request];
        [self sendImplementation:__requestObj requestMgr:__request ];
        if(__request.OutputFault!=nil)
        {
        if(__error)
        {
        *__error=__request.OutputFault;
        }
        return nil;
    }
        DDXMLElement *__result=[TIFHelper getResultElement:__request.OutputBody name:@"PHARMA"];
        return (TIFPHARMA*)[__request createObject:__result type:[TIFPHARMA class]];
    }
    
    -(TIFRequestResultHandler*) GetByPharmacodeAsync:(NSString*) pharmacode lang:(NSString*) lang __target:(id) __target __handler:(SEL) __handler
    {
        /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return nil;
    }
    
    -(TIFRequestResultHandler*) GetByPharmacodeAsync:(NSString*) pharmacode lang:(NSString*) lang __target:(id<TIFSoapServiceResponse>) __target
    {
        /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return nil;
    }
    
    -(NSString*) GetByPharmacode:(NSString*) pharmacode lang:(NSString*) lang __error:(NSError**) __error
    {
        /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return nil;
    }
    
    -(TIFRequestResultHandler*) GetByDescrAsync:(NSString*) descr lang:(NSString*) lang __target:(id) __target __handler:(SEL) __handler
    {
        /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return nil;
    }
    
    -(TIFRequestResultHandler*) GetByDescrAsync:(NSString*) descr lang:(NSString*) lang __target:(id<TIFSoapServiceResponse>) __target
    {
        /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return nil;
    }
    
    -(NSString*) GetByDescr:(NSString*) descr lang:(NSString*) lang __error:(NSError**) __error
    {
        /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return nil;
    }

@end
